version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=payments
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - NODE_ENV=production
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - payments-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payments
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payments-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - payments-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  payments-network:
    driver: bridge 